/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package todomanagerguirebuild.dialogs;

/**
 *
 * @author SCHABT
 */
public class SelectAttachmentStoreModeDialog extends javax.swing.JPanel {

    /**
     * Creates new form SelectAttachmentStoreModeDialog
     */
    public SelectAttachmentStoreModeDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labHeadline = new javax.swing.JLabel();
        radioSaveIntern = new javax.swing.JRadioButton();
        radioSaveLocal = new javax.swing.JRadioButton();
        butSave = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();
        labLongDesc = new javax.swing.JTextArea();

        labHeadline.setText("Wie sollen die hinzugefügten Dateien gespeichert werden?");

        radioSaveIntern.setText("Intern in der Todo-Liste");

        radioSaveLocal.setSelected(true);
        radioSaveLocal.setText("Extern, lokal auf diesem PC");
        radioSaveLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSaveLocalActionPerformed(evt);
            }
        });

        butSave.setText("Speichern");

        butCancel.setText("Abbrechen");

        labLongDesc.setColumns(20);
        labLongDesc.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labHeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radioSaveLocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(butSave)
                                .addGap(18, 18, 18)
                                .addComponent(butCancel))
                            .addComponent(radioSaveIntern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(labLongDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labHeadline)
                        .addGap(18, 18, 18)
                        .addComponent(radioSaveIntern)
                        .addGap(8, 8, 8)
                        .addComponent(radioSaveLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(labLongDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSave)
                    .addComponent(butCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioSaveLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSaveLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSaveLocalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labHeadline;
    private javax.swing.JTextArea labLongDesc;
    private javax.swing.JRadioButton radioSaveIntern;
    private javax.swing.JRadioButton radioSaveLocal;
    // End of variables declaration//GEN-END:variables
}
