/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package todomanagerguirebuild;

/**
 *
 * @author SCHABT
 */
public class TodoListPanel extends javax.swing.JPanel {

    /**
     * Creates new form TodoListPanel
     */
    public TodoListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBoxSelectTodo = new javax.swing.JCheckBox();
        checkBoxSelectPending = new javax.swing.JCheckBox();
        checkBoxSelectWait = new javax.swing.JCheckBox();
        checkBoxSelectAlarm = new javax.swing.JCheckBox();
        checkBoxSelectDone = new javax.swing.JCheckBox();
        labAddTodo = new javax.swing.JLabel();
        txtFieldFilter = new javax.swing.JTextField();
        checkBoxSelectNegotiate = new javax.swing.JCheckBox();
        labExportCsv = new javax.swing.JLabel();
        scrollpaneTodoList = new javax.swing.JScrollPane();
        tableTodoList = new javax.swing.JTable();
        comboBoxSelectCategory = new javax.swing.JComboBox();

        checkBoxSelectTodo.setText("TODO");

        checkBoxSelectPending.setText("PENDING");

        checkBoxSelectWait.setText("WAIT");

        checkBoxSelectAlarm.setText("ALARM");

        checkBoxSelectDone.setText("DONE");

        labAddTodo.setText("X");
        labAddTodo.setMaximumSize(new java.awt.Dimension(6, 16));
        labAddTodo.setMinimumSize(new java.awt.Dimension(6, 16));
        labAddTodo.setPreferredSize(new java.awt.Dimension(6, 16));

        txtFieldFilter.setText("Filter");
        txtFieldFilter.setMaximumSize(new java.awt.Dimension(2147483647, 14));
        txtFieldFilter.setMinimumSize(new java.awt.Dimension(6, 14));
        txtFieldFilter.setPreferredSize(new java.awt.Dimension(30, 14));
        txtFieldFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFilterActionPerformed(evt);
            }
        });

        checkBoxSelectNegotiate.setText("umkehren");

        labExportCsv.setText("X");

        tableTodoList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpaneTodoList.setViewportView(tableTodoList);

        comboBoxSelectCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxSelectCategory.setMaximumSize(new java.awt.Dimension(32767, 14));
        comboBoxSelectCategory.setMinimumSize(new java.awt.Dimension(56, 14));
        comboBoxSelectCategory.setPreferredSize(new java.awt.Dimension(56, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkBoxSelectTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSelectPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSelectWait)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSelectAlarm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSelectDone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAddTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labExportCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSelectNegotiate))
            .addComponent(scrollpaneTodoList)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxSelectTodo)
                    .addComponent(checkBoxSelectPending)
                    .addComponent(checkBoxSelectWait)
                    .addComponent(checkBoxSelectAlarm)
                    .addComponent(checkBoxSelectDone)
                    .addComponent(labAddTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxSelectNegotiate)
                    .addComponent(labExportCsv)
                    .addComponent(txtFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneTodoList, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFilterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxSelectAlarm;
    private javax.swing.JCheckBox checkBoxSelectDone;
    private javax.swing.JCheckBox checkBoxSelectNegotiate;
    private javax.swing.JCheckBox checkBoxSelectPending;
    private javax.swing.JCheckBox checkBoxSelectTodo;
    private javax.swing.JCheckBox checkBoxSelectWait;
    private javax.swing.JComboBox comboBoxSelectCategory;
    private javax.swing.JLabel labAddTodo;
    private javax.swing.JLabel labExportCsv;
    private javax.swing.JScrollPane scrollpaneTodoList;
    private javax.swing.JTable tableTodoList;
    private javax.swing.JTextField txtFieldFilter;
    // End of variables declaration//GEN-END:variables
}
