/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package todomanagerguirebuild.configPanels;

/**
 *
 * @author SCHABT
 */
public class ConfigOverviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfigOverviewPanel
     */
    public ConfigOverviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labShowLockedListsOnStartup = new javax.swing.JLabel();
        chkboxShowLockedListsOnStartup = new javax.swing.JCheckBox();
        chkboxEnableHintsOnStartup = new javax.swing.JCheckBox();

        labShowLockedListsOnStartup.setText("Anzeige von Elementen");

        chkboxShowLockedListsOnStartup.setText("Zeige gesperrte Listen (Box) beim Starten des Programms");
        chkboxShowLockedListsOnStartup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxShowLockedListsOnStartupActionPerformed(evt);
            }
        });

        chkboxEnableHintsOnStartup.setText("Zeige Benutzer-Hinweise beim Starten des Programms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labShowLockedListsOnStartup, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkboxShowLockedListsOnStartup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkboxEnableHintsOnStartup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labShowLockedListsOnStartup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkboxShowLockedListsOnStartup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkboxEnableHintsOnStartup)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkboxShowLockedListsOnStartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxShowLockedListsOnStartupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxShowLockedListsOnStartupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkboxEnableHintsOnStartup;
    private javax.swing.JCheckBox chkboxShowLockedListsOnStartup;
    private javax.swing.JLabel labShowLockedListsOnStartup;
    // End of variables declaration//GEN-END:variables
}
